### ISSUE TITLE
consider updating modules to implement Ansible best practices

### ISSUE THREAD

**Issue by privateip** [Apstra/aos-ansible#6]
Best practices are documented [here](http://docs.ansible.com/ansible/dev_guide/developing_modules.html)

* rename modules to include ```.py``` extension and add ```__init__.py```
* add RETURNS docstring
* add Github handle to author
* update version_added string to "2.3"
* catch import errors and return helpful string
* add ```__name__ == `__main__':``` check
* swap docstring and imports

**Comment by jeremyschulman** [comment]
thank you very much for the issue, and PR!
